#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Adaptive.ReactiveTrader.Client.Android.Resource", IsApplication=true)]

namespace Adaptive.ReactiveTrader.Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notional_background_focused = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notional_background_normal = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notional_background_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notional_textcolor_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int pricebutton_background_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pricebutton_background_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pricebutton_background_selector = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pricebutton_foreground_selector = 2130837512;
			
			// aapt resource value: 0x7f02000c
			public const int red = 2130837516;
			
			// aapt resource value: 0x7f020009
			public const int spottile_background_focused = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int spottile_background_normal = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int spottile_background_selector = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int PriceButtonBigFiguresTextView = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int PriceButtonDirectionTextView = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int PriceButtonPipsTextView = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int PriceButtonTenthOfPipTextView = 2131034115;
			
			// aapt resource value: 0x7f05000b
			public const int SpotTileAskPriceButton = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int SpotTileBidPriceButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int SpotTileCurrencyPairTextView = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int SpotTileDealtCurrencyTextView = 2131034124;
			
			// aapt resource value: 0x7f05000a
			public const int SpotTileDownArrow = 2131034122;
			
			// aapt resource value: 0x7f05000d
			public const int SpotTileNotionalEditText = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int SpotTileSpotDateTextView = 2131034126;
			
			// aapt resource value: 0x7f050007
			public const int SpotTileSpreadLayout = 2131034119;
			
			// aapt resource value: 0x7f050009
			public const int SpotTileSpreadTextView = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int SpotTileUpArrow = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int SpotTilesRecyclerView = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int PriceButton = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ShellView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int SpotTileView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
