#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("Adaptive.ReactiveTrader.Client.Android.Resource", IsApplication=true)]

namespace Adaptive.ReactiveTrader.Client.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dotted = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notional_background_focused = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notional_background_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notional_background_selector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notional_textcolor_selector = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int pricebutton_background_normal = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int pricebutton_background_pressed = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int pricebutton_background_selector = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int pricebutton_foreground_selector = 2130837513;
			
			// aapt resource value: 0x7f02000d
			public const int red = 2130837517;
			
			// aapt resource value: 0x7f02000a
			public const int spottile_background_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int spottile_background_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int spottile_background_selector = 2130837516;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int BlotterRowCurrencyPairTextView = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int BlotterRowDirectionTextView = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int BlotterRowNotionalTextView = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int BlotterRowSpotRateTextView = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int BlotterRowStatusTextView = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int BlotterRowTradeDateTextView = 2131034113;
			
			// aapt resource value: 0x7f050009
			public const int BlotterRowTradeIdTextView = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int BlotterRowTraderNameTextView = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int BlotterRowValueDateTextView = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int BlotterRowsRecyclerView = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int PriceButtonBigFiguresTextView = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int PriceButtonDirectionTextView = 2131034123;
			
			// aapt resource value: 0x7f05000d
			public const int PriceButtonPipsTextView = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int PriceButtonTenthOfPipTextView = 2131034126;
			
			// aapt resource value: 0x7f050016
			public const int SpotTileAskPriceButton = 2131034134;
			
			// aapt resource value: 0x7f050011
			public const int SpotTileBidPriceButton = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int SpotTileCurrencyPairTextView = 2131034128;
			
			// aapt resource value: 0x7f050017
			public const int SpotTileDealtCurrencyTextView = 2131034135;
			
			// aapt resource value: 0x7f050015
			public const int SpotTileDownArrow = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int SpotTileNotionalEditText = 2131034136;
			
			// aapt resource value: 0x7f050019
			public const int SpotTileSpotDateTextView = 2131034137;
			
			// aapt resource value: 0x7f050012
			public const int SpotTileSpreadLayout = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int SpotTileSpreadTextView = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int SpotTileUpArrow = 2131034131;
			
			// aapt resource value: 0x7f05000f
			public const int SpotTilesRecyclerView = 2131034127;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BlotterRowView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BlotterView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int PriceButton = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ShellView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SpotTileView = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
